SELECT P.DNI, P.NOMBRE, P.APELLIDO
FROM PACIENTES P
WHERE NOT EXITS (
  SELECT * FROM 
  MEDICOS M INNERJOIN MEDICOSESPECIALIDADES ME ON (ME.MATRICULA = M.MATRICULA)
  INNERJOIN ESPECIALIDADES E ON (E.IDESPECIALIDAD = ME.IDESPECIALIDAD)
  WHERE E,NOMBREE = 'CARDIOLOGIA' AND NOT EXITS (
    SELECT * FROM ATENCIONES A 
    WHERE A.DNI = P.DNI AND A.MATRICULA = M.MATRICULA
  )
)

