SELECT c.CUIT, c.NOMCLTE, C.EMAIL 
FROM CLIENTE c
WHERE NOT EXITS (
  SELECT * FROM PRODUCTO P
  WHERE NOT EXITS (
    SELECT * PEDIDO PE INNER JOIN PEDPROD PEPR ON (PE.NROPED =  PEDPROD.NROPED)
    WHERE PE.FECHA BETWEEN "2024/12/12" AND "2023/12/12" AND C.NROCLTE = PE.NROCLTE AND P.CODPRODCTO = PEPR.CODPRODCTO
  )
)
